spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/database_parking
    username: postgres
    password: 10092001artem
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

